default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: agendaprouser
  password: agendapro
  pool: 5

development:
  <<: *default
  database: agendapro_db_development

test:
  <<: *default
  database: agendapro_db_tests
